; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf/

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    ESPAsyncWebServer
    AsyncTCP
    ArduinoJson
    esp_now

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
